services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} 
    ports:
      - "${PORT_DB}:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - travel-policy

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - BASEURL=${BACKEND_URL}
      - PORT=${PORT_BACKEND}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PW}@postgres:5432/${POSTGRES_DB}
    volumes:
      - ./backend:/app
    networks:
      - travel-policy
    ports:
      - "${PORT_BACKEND}:3000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_APP_API_URL=${BACKEND_URL}
    volumes:
      - ./frontend:/app
    networks:
      - travel-policy
    ports:
      - "${PORT_FRONTEND}:5173"
    depends_on:
      - api

volumes:
  postgres_data:

networks:
  travel-policy:
    driver: bridge
