version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} 
    ports:
      - "5431:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - travel-policy

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - travel-policy
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_APP_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
    networks:
      - travel-policy
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  postgres_data:

networks:
  travel-policy:
    driver: bridge
